# Generated by Django 4.0.5 on 2022-06-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vydavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Polozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.FloatField(default=0)),
                ('poznamka', models.CharField(max_length=300)),
                ('pub_date', models.CharField(max_length=50)),
                ('vydavok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymoney.vydavky')),
            ],
        ),
    ]
